# Config version, you should never manually change this.
config-version: 6

###############
# Core Config #
###############
# Core config for backend processes or misc options.
# If you are looking to edit graves, the main grave config file is grave.yml.
settings:
  
  ###########
  # Storage #
  ###########
  # Data storage system.
  storage:
    # Available options: SQLITE, MYSQL, MARIADB, POSTGRESQL, H2.
    # More storage types will be added in the future.
    type: SQLITE

    sqlite:
      # Unless you know what you're doing, leave the options under sqlite default.
      # Journal mode for SQLite. Options include DELETE, TRUNCATE, PERSIST, MEMORY, WAL, OFF.
      # Refer to https://www.sqlite.org/pragma.html#pragma_journal_mode for more details.
      journal-mode: "WAL"
      # Synchronous mode for SQLite. Options include 0 (OFF), 1 (NORMAL), 2 (FULL), 3 (EXTRA).
      # Refer to https://www.sqlite.org/pragma.html#pragma_synchronous for more details.
      synchronous: "OFF"

    mysql:
      # Unless you know what you're doing, leave the options under mysql default.
      # Host of the MySQL database.
      host: "localhost"
      # Port for the MySQL database (do not change unless you use a different port).
      port: 3306
      # Database username. Ensure the user has access to the database.
      username: "username"
      # Database password. Case-sensitive.
      password: "password"
      # Database to use.
      database: "graves"
      # Maximum number of connections allowed to the database. 
      # Do not change unless you know what you are doing.
      maxConnections: 10
      # Maximum lifetime of a connection in milliseconds.
      # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      maxLifetime: 1800000
      # Connection timeout in milliseconds.
      # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      # Only increase if your connection keeps timing out.
      connectionTimeout: 30000
      # Should we use SSL? Unless you know what you are doing, leave this at false.
      useSSL: false
      # Should we allow public key retrieval? DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      allowPublicKeyRetrieval: false
      # Should we verify the server certificate? DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      verifyServerCertificate: false

    postgresql:
      # Unless you know what you're doing, leave the options under postgresql default.
      # Host of the PostgreSQL database.
      host: "localhost"
      # Port for the PostgreSQL database (do not change unless you use a different port).
      port: 5432
      # Database username. Ensure the user has access to the database.
      username: "username"
      # Database password. Case-sensitive.
      password: "password"
      # Database to use.
      database: "graves"
      # Maximum number of connections allowed to the database.
      # Do not change unless you know what you are doing.
      maxConnections: 10
      # Maximum lifetime of a connection in milliseconds.
      # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      maxLifetime: 1800000
      # Connection timeout in milliseconds.
      # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      # Only increase if your connection keeps timing out.
      connectionTimeout: 30000
      # Should we use SSL? Unless you know what you are doing, leave this at false.
      ssl: false
      # SSL factory class. Default: org.postgresql.ssl.NonValidatingFactory.
      # Refer to PostgreSQL SSL documentation for more details.
      sslfactory: "org.postgresql.ssl.NonValidatingFactory"
      # SSL mode. Options include disable, allow, prefer, require, verify-ca, verify-full.
      # Refer to PostgreSQL SSL documentation for more details.
      sslmode: "disable"
      # Path to the server root certificate.
      sslrootcert: "/path/to/server.crt"
      # Path to the SSL certificate.
      sslcert: "/path/to/client.crt"
      # Path to the SSL key.
      sslkey: "/path/to/client.key"

    h2:
      # Unless you know what you're doing, leave the options under h2 default.
      # Username for the H2 database.
      username: "sa"
      # Password for the H2 database. The default is an empty string.
      password: ""
      # Maximum number of connections allowed to the database.
      # Do not change unless you know what you are doing.
      maxConnections: 50
      # Maximum lifetime of a connection in milliseconds.
      # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      maxLifetime: 1800000
      # Connection timeout in milliseconds.
      # DO NOT CHANGE UNLESS YOU KNOW WHAT YOU ARE DOING.
      # Only increase if your connection keeps timing out.
      connectionTimeout: 30000

  #########
  # Cache #
  #########
  # Data storage system.
  cache:
    # Cache type. Implementation Unused
    type: NORMAL

  #########
  # Debug #
  #########
  # Debug information, debug level 2 can be useful in finding out why a Grave does not spawn on your server.
  debug:
    # UUID or name of admins to send debug information to. https://mcuuid.net/
    admin:
      - "c59ac6d2-4851-4183-a9f7-15d1a293eed6" # Ranull
      - "069a79f4-44e9-4726-a5be-fca90e38aaf5" # Notch
    # 0 = Nothing, 1 = Information, 2 = Failures
    level: 0

  #########
  # Dump #
  #########
  # Dump server information to help debug the plugin.
  # Methods: MCLOGS, FILE
  dump:
    method: MCLOGS

  ##########
  # Update #
  ##########
  update:
    # Should Graves try and check for an update.
    check: true

  ###########
  # Metrics #
  ###########
  metrics:
    # Should we report metrics to bstats? Available here: https://bstats.org/plugin/bukkit/Graves/12849
    enabled: true

  #################
  # Compatibility #
  #################
  compatibility:
    # Warn when a plugin to have known incompatibilities is detected.
    warning: true

  ###############
  # Integration #
  ###############
  # Enable/Disable integrations into other plugins, if you are having errors relating to another plugin
  # try disabling them here.
  integration:
    # https://multipaper.io/
    multipaper:
      # Should MultiPaper integration be enabled.
      enabled: true
    # https://github.com/PestoNotPasta/MultiCache/
    multicache:
      # Should MultiCache integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/vault.34315/
    vault:
      # Should Vault integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/protocollib.1997/
    protocollib:
      # Should ProtocolLib integration be enabled.
      enabled: true
    # https://dev.bukkit.org/projects/worldedit/
    worldedit:
      # Should WorldEdit integration be enabled.
      enabled: true
      # Should Graves write its schematics into its own folder.
      write: true
    # https://dev.bukkit.org/projects/worldguard/
    worldguard:
      # Should WorldGuard integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/towny-advanced.72694/
    towny:
      # Should Towny integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/griefdefender.68900/
    griefdefender:
      # Should GriefDefender integration be enabled.
      enabled: false
    # https://www.spigotmc.org/resources/furniturelibary.9368/
    furniturelib:
      # Should FurnitureLib integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/furnitureengine.97134/
    furnitureengine:
      # Should FurnitureEngine integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/protectionlib.9368/
    protectionlib:
      # Should ProtectionLib integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/itemsadder.73355/
    itemsadder:
      # Should ItemsAdder integration be enabled.
      enabled: true
      # Should Graves write its data into the ItemsAdder data folder.
      write: true
    # https://www.spigotmc.org/resources/oraxen.72448/
    oraxen:
      # Should Oraxen integration be enabled.
      enabled: true
      # Should Graves write its pack into the Oraxen pack folder.
      write: true
    # https://www.spigotmc.org/resources/placeholderapi.6245/
    placeholderapi:
      # Should PlaceholderAPI integration be enabled.
      enabled: true
    # https://github.com/SkriptLang/Skript/
    skript:
      # Should Skript integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/chestsort.59773/
    chestsort:
      # Should ChestSort integration be enabled.
      enabled: true
    # https://docs.adventure.kyori.net/minimessage/index.html
    minimessage:
      # Should MiniMessage integration be enabled.
      enabled: true
    # https://github.com/Phoenix616/MineDownPlugin/
    minedown:
      # Should MineDown integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/playernpc.93625/
    playernpc:
      # Should PlayerNPC integration be enabled.
      enabled: false
    # https://www.spigotmc.org/resources/citizens.13811/
    citizensnpc:
      # Should Citizens integration be enabled.
      enabled: false
    # https://www.spigotmc.org/resources/itembridge.77080/
    itembridge:
      # Should ItemBridge integration be enabled.
      enabled: true
    # https://luckperms.net/download
    luckperms:
      # Should LuckPerms integration be enabled.
      enabled: true
    # https://www.spigotmc.org/resources/coreprotect.8631/
    coreprotect:
      # Should CoreProtect integration be enabled.
      enabled: true